name: Build & Push Hyperliquid Node to GHCR

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'pruner/**'
      - 'generate_gossip_config.py'
      - 'entrypoint.sh'
      - '.github/workflows/publish.yml'
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Log in to GHCR using a PAT stored in repository secret GHCR_PAT (scopes: write:packages, read:packages).
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/hyperliquid-akash-node:latest
            ghcr.io/${{ github.repository_owner }}/hyperliquid-akash-node:${{ github.sha }} 