name: Build & Push Hyperliquid Node to GHCR

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'pruner/**'
      - 'generate_gossip_config.py'
      - 'entrypoint.sh'
      - '.github/workflows/publish.yml'
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Enable cross-arch builds (arm64 on amd64 runner)
      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      # Log in to GHCR using a PAT stored in repository secret GHCR_PAT (scopes: write:packages, read:packages).
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set version tag
        id: vars
        run: echo "TAG=$(date +'%Y%m%d-%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/hyperliquid-akash-node:latest
            ghcr.io/${{ github.repository_owner }}/hyperliquid-akash-node:${{ steps.vars.outputs.TAG }} 